services:
  forum:
    image: elmehdirezoug/real-time-forum:latest
    # Delete this build block to use the image from the registry instead.
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real-time-forum
    ports:
      - "9070:8082"   # host:container
    volumes:
      - forum-data:/app/backend/database
    restart: always

volumes:
  forum-data:
